debian/tmp/etc/splashy/themes/debian3/         etc/splashy/themes/
debian/tmp/etc/splashy/themes/debian4/         etc/splashy/themes/
debian/tmp/etc/splashy/themes/ubuntusplashy/   etc/splashy/themes/
debian/tmp/etc/splashy/themes/debiansplashy/   etc/splashy/themes/
debian/tmp/etc/splashy/themes/kubuntusplashy/  etc/splashy/themes/
debian/tmp/etc/splashy/themes/crux/            etc/splashy/themes/
