#!/bin/sh

# until we have a debconf question, we won't do this:
# for file in /boot/grub/menu.lst /boot/boot/grub/menu.lst; do
#     if [ -f $file ]
#     then
#         cp $file $file.old
#         sed -e '/^\# nonaltoptions/s/ vga=... //g' $file.old > $file
#         update-grub
#     fi
# done

if [ "$1" = "purge" ] ; then
        update-rc.d splashy remove >/dev/null || exit $?
fi

#DEBHELPER#
